services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile_local
    container_name: go-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
