name: Build and Deploy to ECR and App Runner

on:
    push:
      branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Log in to Amazon ECR
          run: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_BASE_URL }}
    
        - name: Build, tag, and push Docker image to ECR
          env:
              ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
          run: |
            docker build -t $ECR_REPOSITORY_URL:latest .
            docker push $ECR_REPOSITORY_URL:latest
